LogisticsApp/Controllers/CountrieController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LogisticsApp.Models;
using LogisticsApp.Models.General;

namespace LogisticsApp.Controllers
{
    [Authorize]
    public class CountrieController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Countrie
        public ActionResult Index()
        {
            return View(db.countries.Where(w => w.isActive == true).ToList());
        }

        public ActionResult List()
        {

            return View(db.countries.ToList());
        }

        // GET: Countrie/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CountryInformation item = null;
            CountryViewModel model = new CountryViewModel();
            try
            {
                item = db.countryInformations.Single(s => s.Id == id);
                model.Id = item.Country.Id;
                model.Name = item.Country.Name;
                model.imagePath = item.Country.imagePath;
                model.isActive = item.Country.isActive;
                model.State = item.State;
                model.Addressheader = item.Addressheader;
                model.AddressLine1 = item.AddressLine1;
                model.AddressLine2 = item.AddressLine2;
                model.ZIPcode = item.ZIPcode;
                model.City = item.City;
                model.IDNumber = item.IDNumber;
                model.PhoneNumber = item.PhoneNumber;
                model.Semt = item.Semt;
                model.Ilce = item.Ilce;
                model.TaxIDNumber = item.TaxIDNumber;
                model.Area = item.Area;
            }
            catch (Exception)
            {
                model = null;
            }
            return PartialView(model);
        }

        // GET: Countrie/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Countrie/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string name)
        {
            if (String.IsNullOrWhiteSpace(name))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Country country = new Country { Name = name };
            db.countries.Add(country);
            db.SaveChanges();

            CountryInformation info = new CountryInformation { Id = db.countries.First(f => f.Name == name).Id };
            db.countryInformations.Add(info);
            db.SaveChanges();
            TempData["AlertMessage"] = "country "+"\""+country.Name+"\""+" has succesfully created";
            return RedirectToAction("List");

        }

        // POST: Countrie/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CountryViewModel model)
        {
            if (ModelState.IsValid)
            {
                CountryInformation info = null;
                try
                {
                    info = db.countryInformations.Single(s => s.Id == model.Id);
                }
                catch (Exception)
                {
                    ViewBag.AlertMessage = "Something gone wrong. Try again please!";
                    return RedirectToAction("List");
                }
                info.IDNumber = model.IDNumber;
                info.State = model.State;
                info.Addressheader = model.Addressheader;
                info.AddressLine1 = model.AddressLine1;
                info.AddressLine2 = model.AddressLine2;
                info.ZIPcode = model.ZIPcode;
                info.City = model.City;
                info.PhoneNumber = model.PhoneNumber;
                info.Semt = model.Semt;
                info.Ilce = model.Ilce;
                info.TaxIDNumber = model.TaxIDNumber;
                info.Area = model.Area;
                info.Country.Name = model.Name;
                info.Country.isActive = model.isActive;
                if (model.File != null && model.File.ContentLength > 0)
                {
                    var fileExtension = Path.GetExtension(model.File.FileName);
                    var fileName = Path.GetFileNameWithoutExtension(model.File.FileName) + "-" +
                        DateTime.Now.ToString("yyyyMMddHHmmssfff") + fileExtension;
                    var path = Path.Combine(Server.MapPath("~/Img/country"), fileName);
                    model.File.SaveAs(path);
                    info.Country.imagePath = "/Img/country/" + fileName;
                }

                db.SaveChanges();
                TempData["AlertMessage"] = "informations of country " + "\"" + info.Country.Name + "\"" + " has succesfully changed";
                return RedirectToAction("List");
            }
            TempData["AlertMessage"] = "Something gone wrong. Try again please!";
            return RedirectToAction("List");
        }

        // POST: Countrie/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Country country = db.countries.Find(id);
            CountryInformation info = db.countryInformations.Find(id);
            if (country == null)
            {
                return HttpNotFound();
            }

            db.countryInformations.Remove(info);
            db.countries.Remove(country);
            db.SaveChanges();
            return RedirectToAction("List");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LogisticsApp/Views/Countrie/Create.cshtml
@model LogisticsApp.Models.General.Country

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Country</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.imagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.imagePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.imagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isActive)
                    @Html.ValidationMessageFor(model => model.isActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

LogisticsApp/Views/Countrie/Delete.cshtml
@model LogisticsApp.Models.General.Country

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Country</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.imagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imagePath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isActive)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LogisticsApp/Views/Countrie/Details.cshtml
@model LogisticsApp.Models.General.CountryViewModel



@using (Html.BeginForm("Edit", "Countrie", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h1> @Model.Name</h1>
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressLine1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLine1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressLine1, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.AddressLine2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLine2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressLine2, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ZIPcode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ZIPcode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ZIPcode, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Semt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Semt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Semt, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Ilce, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ilce, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ilce, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.IDNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IDNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IDNumber, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Addressheader, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Addressheader, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Addressheader, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.TaxIDNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaxIDNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TaxIDNumber, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Area, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Area, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Area, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isActive, htmlAttributes: new { @class = "control-label col-md-5" })
            <div class="col-md-5">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isActive)
                    @Html.ValidationMessageFor(model => model.isActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.File, htmlAttributes: new { @class = "control-label col-md-12" })
            <div class="row">
                <div class="col-md-5">
                    @Html.TextBoxFor(model => model.File, htmlAttributes: new { @class = "form-control", type = "file" })
                    @Html.ValidationMessageFor(model => model.File, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3">
                    <img src="@Model.imagePath" alt="no picture yet" width="50px" height="50px" />
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<button type="button" id="DeleteCountryBtn" class="btn btn-danger" data-toggle="modal" data-target="#CountryDeleteModal"> Delete country</button>
<div class="modal fade" id="CountryDeleteModal" tabindex="-1" role="dialog" aria-labelledby="CountryDeleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                @using (Html.BeginForm("Delete", "Countrie", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.Id)
                    <div class="form-group">
                        Bu melumatlari silmekde eminsenmi ?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Xeyr</button>
                        <button type="submit" id="" class="btn btn-primary" data-id="">Beli</button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

LogisticsApp/Views/Countrie/Index.cshtml
@model IEnumerable<LogisticsApp.Models.General.Country>

@{
    ViewBag.Title = "Country Index";
  
}

LogisticsApp/Views/Countrie/List.cshtml
@model IEnumerable<LogisticsApp.Models.General.Country>

@{

    Layout = "~/Views/Home/AdminPanel.cshtml";

}

<div id="AdminCountry">
    <div class="row">
        <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#CountryCreateModal"> Add new country</button>
    </div>
    <br /> <br /> 
    <ul class="nav nav-tabs mb-3" id="pills-tab" role="tablist">
        @foreach (var item in Model)
        {
            <li class="nav-item">
                <a class="nav-link btn btn-outline-primary countryInfoBtn" id="pills-home-tab" data-toggle="pill" href="" role="tab" aria-controls="pills-home" data-id="@item.Id" aria-selected="true">@item.Name</a>
            </li>
        }
    </ul>
    <div id="AdminCountryInformations">

    </div>
</div>    
<div class="modal fade" id="CountryCreateModal" tabindex="-1" role="dialog" aria-labelledby="CountryCreateModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="CountryCreateModalLabel">About</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                @using (Html.BeginForm("Create", "Countrie", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    <div class="col-md-12">
                        Olkenin adi : <input class = "form-control" type="text" name="name" value="" placeholder="yaratmaq istediyin olkenin adini daxil et" />
                    </div>
                </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" id="" class="btn btn-primary" data-id="">Create</button>
                    </div>
                }
            </div>

        </div>
    </div>
</div>